# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91d9b27f18265fb1c02faeae15189af7988c557c1b61a5dcb2f406dad9a024a16e2fbff8d608bae6b6835a6a8eed066cc0dd138cfefc5ce715ecb9b4eefef812

test:
  secret_key_base: 1615790c274920d8e8efbcdc6b962f3ddf9e0651727013cc79c8234cdd7ea8b977b5ac6fcf4b9a7b16a4d5e1b5ba9bf48682ca82e71c7e26f4063e4c6c8b89b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  # SODA / NYC Open Data
  soda_domain: "https://explore.data.gov"
  soda_application_token: BoLoWYnV2bSX3orhk9SFzhWSI
  soda_dataset_identifier: rmmq-46n5

  
  
