# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
require 'open-uri'

CompostSite.destroy_all

compost_site_data = JSON.parse(Net::HTTP.get(URI.parse('https://data.cityofnewyork.us/resource/rmmq-46n5.json')))

# Lat and long was generated by Geocoder, check model
compost_site_data.each do |cs|
  sleep(0.2)
  CompostSite.create(
    name: cs['location'],
    address: cs['location_1']['human_address'].gsub('"','').gsub('{address:', '').gsub('city:', ' ').gsub('state:', ' ').gsub('zip:', ' ').gsub('&nbsp;&nbsp;&nbsp;}', '').gsub('&nbsp;}', '').gsub('&nbsp;', '').gsub('&nbsp;&nbsp;}', '').gsub('&amp;', ''),
    days: cs['days'],
    hours: cs['hours'],
    organizer: cs['organizer'],
    composted_by: cs['composted_by']
  )
end