require 'open-uri'

CompostSite.destroy_all
FoodDonation.destroy_all

compost_site_data = JSON.parse(Net::HTTP.get(URI.parse('https://data.cityofnewyork.us/resource/rmmq-46n5.json')))

# Lat and long was generated by Geocoder, check model
compost_site_data.each do |cs|
  CompostSite.create(
    name: cs['location'],
    address: cs['location_1']['human_address'].gsub('"','').gsub('{address:', '').gsub('city:', ' ').gsub('state:', ' ').gsub('zip:', ' ').gsub('&nbsp;&nbsp;&nbsp;}', '').gsub('&nbsp;}', '').gsub('&nbsp;', '').gsub('&nbsp;&nbsp;}', '').gsub('&amp;', ''),
    days: cs['days'],
    hours: cs['hours'],
    organizer: cs['organizer'],
    composted_by: cs['composted_by']
  )
end


# names = Array.new

# doc = Nokogiri::XML(open("http://ws.feedingamerica.org/FAWebService.asmx/GetAllOrganizations"))

# names = doc.xpath("//div[contains(@class,'results-box'/div[contains(@class, 'name')/a").collect { |name| name.text.strip }
# binding.pry

# doc.css("div.results-box").each do |center|
#   FoodDonation.create(
#     name: center.css("div.name a").text
#   )
# end

# FoodDonation.create(name: "Jon", address: "dfsfdsf", url: "dfshjfshi", latitude: 1.92237, longitude: 1.23232, phone: "212-212-1212")